In [ ]:
import ComplexKmeans

import cv2
import numpy as np
import pptk
import pandas as pd

from sklearn.cluster import KMeans

from tkinter import *
from tkinter import filedialog

from tkinter import ttk

from PIL import Image, ImageTk

import matplotlib
import matplotlib.pyplot as plt
import pptk


class Paint(Frame):
    def initial_points(self):
        self.start_x = -1
        self.start_y = -1
        self.finish_x = -1
        self.finish_y = -1

    def __init__(self, parent):
        ttk.Frame.__init__(self, parent)
        self.initial_points()
        self.polygone = []
        self.line = None
        self.crop_active = False
        self.img = None
        self.image = None
        self.image_path = None

        self.parent = parent
        self.color = "black"
        self.brush_size = 2
        self.setUI()
        self._draw_image()

        self.ph = None
        self.shape = None
        
        # Simple KMeans config
        self._num_clusters = 4
        
        # Complex Kmeans config
        self.n_clusters = 1
        self.n_lines = 3
        self.n_init = 6
        self.max_iter = 10
        

    def rgb_cube(self):
        X = [[0, 0, i, j, k] for i in range(0, 255)
             for j in {0, 255} for k in {0, 255}]
        Y = [[0, 0, j, i, k] for i in range(0, 255)
             for j in {0, 255} for k in {0, 255}]
        Z = [[0, 0, j, k, i] for i in range(0, 255)
             for j in {0, 255} for k in {0, 255}]
        return np.vstack((X, Y, Z))

    def set_crop(self, status):
        self.crop_active = status

        if (status is True):
            self.polygone = []

    def set_color(self, new_color):
        self.color = new_color

    def set_brush_size(self, new_size):
        self.brush_size = new_size

    def _draw_image(self):
        if (self.image is None):
            return
        self.canv.create_image(0, 0, anchor="nw", image=self.image)

    def draw(self, event):
        if (self.crop_active is False):
            return

        self.polygone.append((event.x, event.y))
        if (self.start_x != -1 or self.start_y != -1):
            self.finish_x = self.start_x
            self.finish_y = self.start_y

        self.start_x = event.x
        self.start_y = event.y

        if not self.line:
            self.line = self.canv.create_line(
                self.start_x,
                self.start_y,
                event.x,
                event.y,
                dash=(4, 2),
                fill=self.color,
                width=5)

        self.canv.create_oval(event.x - self.brush_size,
                              event.y - self.brush_size,
                              event.x + self.brush_size,
                              event.y + self.brush_size,
                              fill=self.color, outline=self.color)

    def draw_line(self, event):
        self.crop(event)
        if (self.crop_active is False):
            return

        if (self.start_x == -1 or self.start_y == -1):
            return
        self.canv.coords(self.line,
                         self.start_x,
                         self.start_y,
                         event.x,
                         event.y)

    def on_button_release(self, event):
        if (self.crop_active is False):
            return

        if (self.finish_x != -1 or self.finish_y != -1):
            self.canv.create_line(self.start_x,
                                  self.start_y,
                                  self.finish_x,
                                  self.finish_y,
                                  dash=(4, 2),
                                  fill=self.color,
                                  width=5)

    def on_right_button_press(self, event):
        self.initial_points()
        self.set_crop(False)
        self.canv.coords(self.line, 0, 0, 0, 0)
        self.line = None

    def print_polygone(self):
        if (len(self.polygone) == 0):
            return
        print(self.polygone)
        print(self.image_path)
        image = cv2.cvtColor(np.array(self.img_resize), cv2.COLOR_RGB2BGR)

        mask = np.zeros(image.shape, dtype=np.uint8)

        roi_corners = np.array([self.polygone], dtype=np.int32)
        channel_count = image.shape[2]
        ignore_mask_color = (255,)*channel_count
        cv2.fillPoly(mask, roi_corners, ignore_mask_color)

        result = cv2.bitwise_and(image, mask)
        result[mask == 0] = 255

        cv2.imshow('result', result)
        cv2.waitKey()

        colourImg = Image.fromarray(result)

        colourPixels = colourImg.convert("RGB")
        colourArray = np.array(colourPixels.getdata()).reshape(
            colourImg.size + (3,))
        indicesArray = np.moveaxis(np.indices(colourImg.size), 0, 2)
        imgArray = np.dstack((indicesArray, colourArray)).reshape((-1, 5))
        # add rgb cube
        self.allArray = np.vstack((imgArray, self.rgb_cube()))

    def draw_cluster(self):
        mean_df = self.df.groupby('y_kmeans')['red', 'green', 'blue'].mean()
        
        for cluster in self.set_colours:
            try:
                self.df.loc[self.df['y_kmeans'] == cluster, 'red_cluster'] = mean_df.loc[cluster][0]
                self.df.loc[self.df['y_kmeans'] == cluster, 'green_cluster'] = mean_df.loc[cluster][1]
                self.df.loc[self.df['y_kmeans'] == cluster, 'blue_cluster'] = mean_df.loc[cluster][2]
            except:
                print(f'Cluster {cluster} is empty')
                continue
        
        self.draw_df(self.df[['red', 'green', 'blue']], self.df[['red_cluster', 'green_cluster', 'blue_cluster']] / 255)

    def draw_df(self, df, colour):
        v = pptk.viewer(df, colour)
        v.set(point_size=0.3)

        
    def draw_rgb_poly(self):
        print(self.allArray)
        src_df = self.generate_df(self.img, True)
        
        df = pd.DataFrame(self.allArray,
                          columns=["y", "x", "blue", "green", "red"])
        x_set= df[["x"]].stack().tolist()
        y_set= df[["y"]].stack().tolist()
        
        colourPixels = self.img.convert("RGB")
        colourArray = np.array(colourPixels.getdata()).reshape(
                self.img.size + (3,))
        indicesArray = np.moveaxis(np.indices(self.img.size), 0, 2)
        imgArray = np.dstack((indicesArray, colourArray)).reshape((-1, 5))
                              
        rows_list = []
        for i in imgArray:
            if i[0] not in y_set and i[1] not in x_set:
                rows_list.append(1)
            else:
                rows_list.append(0)
                
        src_df["temp"] = rows_list
        
        src_df.loc[src_df['temp'] == 1, 'red_temp'] = 0
        src_df.loc[src_df['temp'] == 1, 'green_temp'] = 0
        src_df.loc[src_df['temp'] == 1, 'blue_temp'] = 0
        
        src_df.loc[src_df['temp'] == 0, 'red_temp'] = 255
        src_df.loc[src_df['temp'] == 0, 'green_temp'] = 255
        src_df.loc[src_df['temp'] == 0, 'blue_temp'] = 255
        
        self.draw_df(src_df[['red', 'green', 'blue']], df[['red_temp', 'green_temp', 'blue_temp']] / 255.)

    def draw_rgb(self):
        df = self.generate_df(self.img, True)
        self.draw_df(df[['red', 'green', 'blue']], df[['red', 'green', 'blue']] / 255.)
        
    def generate_picture(self):
        mean_df = self.df.groupby('y_kmeans')['red', 'green', 'blue'].mean()
        print(mean_df)
        for cluster in self.set_colours:
            try:
                self.df.loc[self.df['y_kmeans'] == cluster, 'red_cluster'] = mean_df.loc[cluster][0]
                self.df.loc[self.df['y_kmeans'] == cluster, 'green_cluster'] = mean_df.loc[cluster][1]
                self.df.loc[self.df['y_kmeans'] == cluster, 'blue_cluster'] = mean_df.loc[cluster][2]
            except e:
                #print(f'Cluster {cluster} is empty')
                print(e)
                continue
        test = (self.df[['red_cluster','green_cluster', 'blue_cluster']]).to_numpy().reshape(self.image_path.size[::-1] + (3, ))
        return test

    

    def cluster_complex(self):
        #if "y_kmeans" not in self.df:
        X = self.df[['red', 'green', 'blue']].to_numpy()
        kmean_test = ComplexKmeans.ComplexKmeans(n_clusters=self.n_clusters, n_lines=self.n_lines, max_iter=self.max_iter, n_init=self.n_init)
        [colours, new_planes, new_centroids, array_lines, array_centroids] = kmean_test.fit(X)
        self.df["y_kmeans"] = colours
        self.set_colours = set(colours)
            
        self.test = self.generate_picture()
        self.ph = ImageTk.PhotoImage(image=Image.fromarray((self.test).astype(np.uint8), mode='RGB'))
        self.canv_cluster.create_image(0, 0, anchor="nw", image=self.ph)
        
        
    def cluster(self):
        #if "y_kmeans" not in self.df:
        kmeans = KMeans(n_clusters=self._num_clusters)
        kmeans.fit(self.df[['red', 'green', 'blue']])
        y_kmeans = kmeans.predict(self.df[['red', 'green', 'blue']])
        self.df["y_kmeans"] = y_kmeans
        self.set_colours = set(y_kmeans)
        self.test = self.generate_picture()
        self.ph = ImageTk.PhotoImage(image=Image.fromarray((self.test).astype(np.uint8), mode='RGB'))
        self.canv_cluster.create_image(0, 0, anchor="nw", image=self.ph)
        

    def openfn(self):
        filename = filedialog.askopenfilename(title='open')
        return filename

    def generate_df(self, img, rgb):
        colourPixels = img.convert("RGB")
        colourArray = np.array(colourPixels.getdata()).reshape(
                img.size + (3,))
        indicesArray = np.moveaxis(np.indices(img.size), 0, 2)
        imgArray = np.dstack((indicesArray, colourArray)).reshape((-1, 5))
        if rgb:
            allArray = np.vstack((imgArray, self.rgb_cube()))
        else:
            allArray = imgArray

        return pd.DataFrame(allArray,
                            columns=["y", "x", "red", "green", "blue"])

    def open_image(self):
        self.canv.delete("all")
        try:
            path = self.openfn()
            self.img = Image.open(path)
            self.image_path = self.img
            new_width, new_height = self.img.size
            self.img_resize = self.img.copy()
            self.image = ImageTk.PhotoImage(self.img)
            
            img_width, img_height = self.img.size
            scale_w = self.canv.winfo_width() / img_width
            scale_h = self.canv.winfo_height() / img_height
            scale = min(scale_w, scale_h)
            copy_of_image = self.img.copy()
            image = copy_of_image.resize((int(img_width*scale), int(img_height*scale)))
            self.img_resize = image.copy()
            self.image = ImageTk.PhotoImage(image)
                        
            self._draw_image()
            self.polygone = []
            self.ph = None
            self.df = self.generate_df(self.img, False)
        except e:
            print("Could not open file" + e)

    def setUI(self):
        self.parent.title("RGB Cube")
        self.pack(expand=1, fill=BOTH)

        self.columnconfigure(7, weight=1)
        self.columnconfigure(16, weight=1)
        self.rowconfigure(2, weight=1)

        self.canv = Canvas(self, bg="white", cursor="cross")
        self.canv.grid(row=2, column=0, columnspan=8,
                       padx=5, pady=5, sticky=E+W+S+N)

        self.canv_cluster = Canvas(self, bg="white", cursor="cross")
        self.canv_cluster.grid(row=2, column=9, columnspan=8,
                               padx=5, pady=5, sticky=E+W+S+N)

        self.canv.bind("<ButtonPress-1>", self.draw)
        self.canv.bind("<ButtonPress-3>", self.on_right_button_press)
        self.canv.bind("<Motion>", self.draw_line)
        self.canv.bind("<ButtonRelease-1>", self.on_button_release)

        color_lab = ttk.Label(self, text="Image: ")
        color_lab.grid(row=0, column=0, padx=6)

        red_btn = ttk.Button(self, text="Open", width=10,
                             command=self.open_image)
        red_btn.grid(row=0, column=1)

        green_btn = ttk.Button(self, text="Crop", width=10,
                               command=lambda: self.set_crop(True))
        green_btn.grid(row=0, column=2)

        clear_btn = ttk.Button(self, text="Clear all", width=10,
                               command=lambda: self.canv.delete("all"))
        clear_btn.grid(row=0, column=6, sticky=W)

        size_lab = ttk.Label(self, text="Draw: ")
        size_lab.grid(row=1, column=0, padx=5)
        one_btn = ttk.Button(self, text="RGB", width=10,
                             command=self.draw_rgb)
        one_btn.grid(row=1, column=1)

        two_btn = ttk.Button(self, text="RGB Poly", width=10,
                             command=self.draw_rgb_poly)
        two_btn.grid(row=1, column=2)

        twenty_btn = ttk.Button(self, text="Draw Poly", width=10,
                                command=self.print_polygone)
        twenty_btn.grid(row=1, column=6, sticky=W)

        draw_cluster_btn = ttk.Button(self, text="Draw Cluster", width=15,
                                      command=self.draw_cluster)
        draw_cluster_btn.grid(row=1, column=7, sticky=W)

        cluster_btn = ttk.Button(self, text="Cluster", width=10,
                                 command=self.cluster)
        cluster_btn.grid(row=0, column=6, sticky=W)
        
        complex_cluster_btn = ttk.Button(self, text="Complex Cluster", width=15,
                                 command=self.cluster_complex)
        complex_cluster_btn.grid(row=0, column=7, sticky=W)

        #self.comboExample = ttk.Combobox(self,
        #                                 values=[0, 1, 2, 3])
        #self.comboExample.grid(row=1, column=7)
        #self.comboExample.current(0)

        self.zoomcycle = 0
        self.zimg_id = None

        self.canv.bind("<MouseWheel>", self.zoomer)

        self.canv.bind('<Configure>', self.resize_image)

    def zoomer(self, event):
        if (event.delta > 0):
            if self.zoomcycle != 4:
                self.zoomcycle += 1
        elif (event.delta < 0):
            if self.zoomcycle != 0:
                self.zoomcycle -= 1
        self.crop(event)

    def crop(self, event):
        if self.zimg_id:
            self.canv.delete(self.zimg_id)
        if (self.zoomcycle) != 0:
            x, y = event.x, event.y
            if self.zoomcycle == 1:
                tmp = self.img_resize.crop((x - 45, y - 30, x + 45, y + 30))
            elif self.zoomcycle == 2:
                tmp = self.img_resize.crop((x - 30, y - 20, x + 30, y + 20))
            elif self.zoomcycle == 3:
                tmp = self.img_resize.crop((x - 15, y - 10, x + 15, y + 10))
            elif self.zoomcycle == 4:
                tmp = self.img_resize.crop((x - 6, y - 4, x + 6, y + 4))
            size = 300, 200
            self.zimg = ImageTk.PhotoImage(tmp.resize(size))
            self.zimg_id = self.canv.create_image(event.x, event.y, image=self.zimg)

    def resize_image(self, event):
        if self.img is None:
            return
        new_width = event.width
        new_height = event.height
        img_width, img_height = self.img.size
        scale_w = new_width / img_width
        scale_h = new_height / img_height
        scale = min(scale_w, scale_h)
        copy_of_image = self.img.copy()
        image = copy_of_image.resize((int(img_width*scale), int(img_height*scale)))
        self.img_resize = image.copy()
        self.image = image.copy()
        photo = ImageTk.PhotoImage(image)
        self.canv.create_image(0, 0, anchor="nw", image=photo)
        self.canv.image = photo
        # avoid garbage collection
        if "y_kmeans" not in self.df:
            return
        copy_of_cluster = Image.fromarray((self.test).astype(np.uint8), mode='RGB').copy()
        self.ph_resize = copy_of_cluster.resize((int(img_width*scale), int(img_height*scale)))
        self.ph = self.ph_resize.copy()
        cluster = ImageTk.PhotoImage(self.ph_resize)
        self.canv_cluster.create_image(0, 0, anchor="nw", image=cluster)
        self.canv_cluster.image = cluster
        
        # avoid garbage collection


def main():
    root = Tk()
    root.geometry("850x500+300+300")
    app = Paint(root)
    root.mainloop()


if __name__ == '__main__':
    main()


DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'sRGB' 41 1
DEBUG:PIL.PngImagePlugin:STREAM b'gAMA' 54 4
DEBUG:PIL.PngImagePlugin:STREAM b'pHYs' 70 9
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 91 65445


1


DEBUG:root:Iteration: 0
DEBUG:root:Centroid 0: [137.76975864 133.02636515 128.86154094]
DEBUG:root:Plane 0: [-0.25639819  0.79674728 -0.54722366]
DEBUG:root:Variance: 5.290233155340876
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 0: [137.76975864 133.02636515 128.86154094]
DEBUG:root:Plane 0: [-0.25639819  0.79674728 -0.54722366]
DEBUG:root:Variance: 5.290233155340876
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [137.76975864 133.02636515 128.86154094]
DEBUG:root:Plane 0: [-0.25639819  0.79674728 -0.54722366]
DEBUG:root:Variance: 5.290233155340876
DEBUG:root:Iteration: 3
DEBUG:root:Centroid 0: [137.76975864 133.02636515 128.86154094]
DEBUG:root:Plane 0: [-0.25639819  0.79674728 -0.54722366]
DEBUG:root:Variance: 5.290233155340876
DEBUG:root:Iteration: 4
DEBUG:root:Centroid 0: [137.76975864 133.02636515 128.86154094]
DEBUG:root:Plane 0: [-0.25639819  0.79674728 -0.54722366]
DEBUG:root:Variance: 5.290233155340876
DEBUG:root:Iteration: 5
DEBUG:root:Centroid 0: [137.76975864 133.02636515 1

DEBUG:root:Plane 0: [-0.25639819  0.79674728 -0.54722366]
DEBUG:root:Variance: 5.290233155340876
DEBUG:root:Iteration: 5
DEBUG:root:Centroid 0: [137.76975864 133.02636515 128.86154094]
DEBUG:root:Plane 0: [-0.25639819  0.79674728 -0.54722366]
DEBUG:root:Variance: 5.290233155340876
DEBUG:root:Iteration: 6
DEBUG:root:Centroid 0: [137.76975864 133.02636515 128.86154094]
DEBUG:root:Plane 0: [-0.25639819  0.79674728 -0.54722366]
DEBUG:root:Variance: 5.290233155340876
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 0: [137.76975864 133.02636515 128.86154094]
DEBUG:root:Plane 0: [-0.25639819  0.79674728 -0.54722366]
DEBUG:root:Variance: 5.290233155340876
DEBUG:root:Iteration: 8
DEBUG:root:Centroid 0: [137.76975864 133.02636515 128.86154094]
DEBUG:root:Plane 0: [-0.25639819  0.79674728 -0.54722366]
DEBUG:root:Variance: 5.290233155340876
DEBUG:root:Iteration: 9
DEBUG:root:Centroid 0: [137.76975864 133.02636515 128.86154094]
DEBUG:root:Plane 0: [-0.25639819  0.79674728 -0.54722366]
DEBUG:root:Varian

[1.04736749 0.36796216 0.51598372]
[129.43777927  56.99974756 219.01200966]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 0: [129.43777927  56.99974756 219.01200966]
DEBUG:root:Line 0: [1.04736749 0.36796216 0.51598372]
DEBUG:root:Variance ratio: [0.97296332 0.02173064 0.00530605]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 1: [104.35593722 169.49666864 197.14347054]
DEBUG:root:Line 1: [-0.40083231 -0.66458017 -0.63060816]
DEBUG:root:Variance ratio: [0.98858073 0.00881165 0.00260762]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 2: [143.3195681  136.38892418 131.39492193]
DEBUG:root:Line 2: [0.55307709 0.58147424 0.59665185]
DEBUG:root:Variance ratio: [0.97340562 0.0219532  0.00464117]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 3: [99.18559012 90.34878448 82.82219423]
DEBUG:root:Line 3: [-0.55919097 -0.57291956 -0.59922336]
DEBUG:root:Variance: 155.18522568731453
DEBUG:root:Variance ratio: 0.0650503299945529


[-0.06169498  0.36548314 -0.23457383]
[129.43777927  56.99974756 219.01200966]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 0: [129.43777927  56.99974756 219.01200966]
DEBUG:root:Line 0: [-0.06169498  0.36548314 -0.23457383]
DEBUG:root:Variance ratio: [0.9764129  0.02015518 0.00343192]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 1: [103.42424913 168.39104125 195.88901188]
DEBUG:root:Line 1: [-0.39700779 -0.66039311 -0.6373898 ]
DEBUG:root:Variance ratio: [0.99264526 0.00529984 0.0020549 ]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 2: [139.56247402 133.45945309 129.52763176]
DEBUG:root:Line 2: [-0.55246572 -0.58586905 -0.59290731]
DEBUG:root:Variance ratio: [9.97611434e-01 1.39612556e-03 9.92440330e-04]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 3: [138.1981625  129.85127699 123.0293689 ]
DEBUG:root:Line 3: [0.55603799 0.57056194 0.60438466]
DEBUG:root:Variance: 130.38720629953286
DEBUG:root:Variance ratio: 0.0333304038907102
DEBUG:root:Variance ratio: [0.66816931 0.25623048 0.07560021]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [123.31868132 142.73626374 162

DEBUG:root:Variance ratio: [0.97521166 0.01785301 0.00693533]
DEBUG:root:Iteration: 10
DEBUG:root:Centroid 0: [ 85.27958063 108.48077883 116.94558163]
DEBUG:root:Line 0: [0.51134219 0.58977006 0.62506035]
DEBUG:root:Variance ratio: [9.81114457e-01 1.80979128e-02 7.87629907e-04]
DEBUG:root:Iteration: 10
DEBUG:root:Centroid 1: [105.80043367 173.68856409 202.68414712]
DEBUG:root:Line 1: [-0.41302592 -0.68177316 -0.60381698]
DEBUG:root:Variance ratio: [0.99469256 0.00328825 0.00201919]
DEBUG:root:Iteration: 10
DEBUG:root:Centroid 2: [135.68265075 129.50909631 126.04974179]
DEBUG:root:Line 2: [-0.54649455 -0.58015155 -0.60396016]
DEBUG:root:Variance ratio: [0.99754706 0.00136769 0.00108525]
DEBUG:root:Iteration: 10
DEBUG:root:Centroid 3: [141.35218179 133.49899171 126.98017949]
DEBUG:root:Line 3: [-0.54730984 -0.57591095 -0.60727137]
DEBUG:root:Variance: 245.78781307655976
DEBUG:root:Variance ratio: 0.05143426802936171
DEBUG:root:Variance ratio: [0.97562887 0.01752957 0.00684156]
DEBUG:root

[ 0.0603771   0.40379056 -0.02765227]
[245.64625801  31.2991971   95.37931735]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 2: [245.64625801  31.2991971   95.37931735]
DEBUG:root:Line 2: [ 0.0603771   0.40379056 -0.02765227]
DEBUG:root:Variance: 909.0240513867324
DEBUG:root:Variance ratio: 0.4112600986573411
DEBUG:root:Variance ratio: [0.97514879 0.02329676 0.00155446]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [138.04481801 131.23310611 126.08620965]
DEBUG:root:Line 0: [-0.56465935 -0.57656624 -0.59053466]
DEBUG:root:Variance ratio: [0.8011448  0.19179956 0.00705564]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 1: [132.85437161 165.07240048 178.45747908]
DEBUG:root:Line 1: [-0.14675631  0.59406929  0.79091356]


[-0.01292036  0.52889772  0.74936175]
[245.64625801  31.2991971   95.37931735]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 2: [245.64625801  31.2991971   95.37931735]
DEBUG:root:Line 2: [-0.01292036  0.52889772  0.74936175]
DEBUG:root:Variance: 677.7158392632842
DEBUG:root:Variance ratio: 0.22370641171159308
DEBUG:root:Variance ratio: [0.98244421 0.01597362 0.00158217]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [138.51105657 131.59615817 126.41591732]
DEBUG:root:Line 0: [-0.56173302 -0.57678699 -0.59310436]
DEBUG:root:Variance ratio: [0.82706751 0.1625523  0.01038019]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 1: [117.51721283 172.10017247 195.67692308]
DEBUG:root:Line 1: [0.17293452 0.68661157 0.70615735]


[-0.06461732  0.22139335  0.03327018]
[245.64625801  31.2991971   95.37931735]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 2: [245.64625801  31.2991971   95.37931735]
DEBUG:root:Line 2: [-0.06461732  0.22139335  0.03327018]
DEBUG:root:Variance: 630.4679406080093
DEBUG:root:Variance ratio: 0.1904882825993675
DEBUG:root:Variance ratio: [0.99216065 0.00624681 0.00159253]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [138.8773902  131.78641789 126.52842538]
DEBUG:root:Line 0: [-0.5536193  -0.57714297 -0.60034295]
DEBUG:root:Variance ratio: [0.96246602 0.02859351 0.00894046]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 1: [105.3705969  169.29587325 197.10714812]
DEBUG:root:Line 1: [-0.37775877 -0.67504935 -0.63372446]


[1.16835286 0.77580107 1.3004427 ]
[245.64625801  31.2991971   95.37931735]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 2: [245.64625801  31.2991971   95.37931735]
DEBUG:root:Line 2: [1.16835286 0.77580107 1.3004427 ]
DEBUG:root:Variance: 179.76905649916569
DEBUG:root:Variance ratio: 0.04537332209791653
DEBUG:root:Variance ratio: [0.9929323  0.00548173 0.00158597]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [138.95554005 131.82837878 126.57963737]
DEBUG:root:Line 0: [-0.55085912 -0.57787609 -0.60217394]
DEBUG:root:Variance ratio: [0.97602067 0.02031019 0.00366914]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 1: [103.24255319 167.90895084 195.30528247]
DEBUG:root:Line 1: [-0.39420007 -0.65945954 -0.64009329]


[-0.52657496  0.26530648 -0.41117463]
[245.64625801  31.2991971   95.37931735]
Lose


DEBUG:root:Iteration: 11
DEBUG:root:Centroid 2: [245.64625801  31.2991971   95.37931735]
DEBUG:root:Line 2: [-0.52657496  0.26530648 -0.41117463]
DEBUG:root:Variance: 131.73906446415688
DEBUG:root:Variance ratio: 0.03104703020321265
DEBUG:root:Variance ratio: [0.87557441 0.11976055 0.00466503]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 0: [118.29619923 116.23120501 112.976527  ]
DEBUG:root:Line 0: [0.22826593 0.60719632 0.76105669]
DEBUG:root:Variance ratio: [0.9682824  0.02474685 0.00697075]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 1: [152.20489077 145.47608484 140.63659809]
DEBUG:root:Line 1: [0.51956237 0.59127376 0.61680652]
DEBUG:root:Variance: 246.49325170066064
DEBUG:root:Variance ratio: 0.15614318412986988
DEBUG:root:Variance ratio: [0.93633057 0.05949531 0.00417412]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [114.251011   125.17682074 128.04455951]
DEBUG:root:Line 0: [0.05370285 0.59594086 0.80123061]
DEBUG:root:Variance ratio: [0.98876803 0.00965467 0.0015773 ]
DEBUG:

DEBUG:root:Variance ratio: [0.97633751 0.02023862 0.00342387]
DEBUG:root:Iteration: 6
DEBUG:root:Centroid 0: [103.1746789  167.86957798 195.24227523]
DEBUG:root:Line 0: [-0.39430798 -0.65889636 -0.6406066 ]
DEBUG:root:Variance ratio: [0.99290566 0.00550811 0.00158623]
DEBUG:root:Iteration: 6
DEBUG:root:Centroid 1: [138.95742027 131.83018502 126.58266625]
DEBUG:root:Line 1: [-0.55079074 -0.57790208 -0.60221155]
DEBUG:root:Variance: 130.79037271369143
DEBUG:root:Variance ratio: 0.030756833971975154
DEBUG:root:Variance ratio: [0.97634145 0.02023405 0.0034245 ]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 0: [103.1845544  167.89061812 195.26838937]
DEBUG:root:Line 0: [-0.39442417 -0.6589521  -0.64047772]
DEBUG:root:Variance ratio: [0.9929021  0.00551151 0.00158639]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 1: [138.95681084 131.82973529 126.58228894]
DEBUG:root:Line 1: [-0.55080432 -0.57789972 -0.6022014 ]
DEBUG:root:Variance: 130.66959578784034
DEBUG:root:Variance ratio: 0.030756455682401

DEBUG:root:Variance ratio: [0.99289857 0.00551475 0.00158667]
DEBUG:root:Iteration: 11
DEBUG:root:Centroid 1: [138.9561737  131.82926792 126.58187888]
DEBUG:root:Line 1: [-0.55081889 -0.57789655 -0.60219111]
DEBUG:root:Variance: 130.54888459629797
DEBUG:root:Variance ratio: 0.030757789877222597
DEBUG:root:Variance ratio: [0.97466393 0.02359091 0.00174516]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 0: [138.39536291 131.63449269 126.59731195]
DEBUG:root:Line 0: [-0.56289244 -0.57611458 -0.5926585 ]
DEBUG:root:Variance ratio: [0.96838179 0.02496254 0.00665568]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 1: [113.96489726 185.98848935 215.01769406]
DEBUG:root:Line 1: [0.43689333 0.71662316 0.54366853]
DEBUG:root:Variance: 114.12422505340169
DEBUG:root:Variance ratio: 0.05695427935797704
DEBUG:root:Variance ratio: [0.99186244 0.00647003 0.00166753]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [138.85058368 131.76044621 126.52782762]
DEBUG:root:Line 0: [-0.55348558 -0.57735528 -0.6002621 ]

                 red       green        blue
y_kmeans                                    
2         138.926033  131.807461  126.563921
3         103.695910  168.945818  196.569287


DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'sRGB' 41 1
DEBUG:PIL.PngImagePlugin:STREAM b'gAMA' 54 4
DEBUG:PIL.PngImagePlugin:STREAM b'pHYs' 70 9
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 91 65445


1


DEBUG:root:Iteration: 0
DEBUG:root:Centroid 0: [57.47781155 70.08349064 54.84007359]
DEBUG:root:Plane 0: [ 0.23356401 -0.7490862   0.61993364]
DEBUG:root:Variance: 3.063556558808087
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 0: [57.47781155 70.08349064 54.84007359]
DEBUG:root:Plane 0: [ 0.23356401 -0.7490862   0.61993364]
DEBUG:root:Variance: 3.063556558808087
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [57.47781155 70.08349064 54.84007359]
DEBUG:root:Plane 0: [ 0.23356401 -0.7490862   0.61993364]
DEBUG:root:Variance: 3.063556558808087
DEBUG:root:Iteration: 3
DEBUG:root:Centroid 0: [57.47781155 70.08349064 54.84007359]
DEBUG:root:Plane 0: [ 0.23356401 -0.7490862   0.61993364]
DEBUG:root:Variance: 3.063556558808087
DEBUG:root:Iteration: 4
DEBUG:root:Centroid 0: [57.47781155 70.08349064 54.84007359]
DEBUG:root:Plane 0: [ 0.23356401 -0.7490862   0.61993364]
DEBUG:root:Variance: 3.063556558808087
DEBUG:root:Iteration: 5
DEBUG:root:Centroid 0: [57.47781155 70.08349064 54.84007359]
DEBUG

DEBUG:root:Centroid 0: [57.47781155 70.08349064 54.84007359]
DEBUG:root:Plane 0: [ 0.23356401 -0.7490862   0.61993364]
DEBUG:root:Variance: 3.063556558808087
DEBUG:root:Iteration: 6
DEBUG:root:Centroid 0: [57.47781155 70.08349064 54.84007359]
DEBUG:root:Plane 0: [ 0.23356401 -0.7490862   0.61993364]
DEBUG:root:Variance: 3.063556558808087
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 0: [57.47781155 70.08349064 54.84007359]
DEBUG:root:Plane 0: [ 0.23356401 -0.7490862   0.61993364]
DEBUG:root:Variance: 3.063556558808087
DEBUG:root:Iteration: 8
DEBUG:root:Centroid 0: [57.47781155 70.08349064 54.84007359]
DEBUG:root:Plane 0: [ 0.23356401 -0.7490862   0.61993364]
DEBUG:root:Variance: 3.063556558808087
DEBUG:root:Iteration: 9
DEBUG:root:Centroid 0: [57.47781155 70.08349064 54.84007359]
DEBUG:root:Plane 0: [ 0.23356401 -0.7490862   0.61993364]
DEBUG:root:Variance: 3.063556558808087
DEBUG:root:Iteration: 0
DEBUG:root:Centroid 0: [57.47781155 70.08349064 54.84007359]
DEBUG:root:Plane 0: [ 0.23356

DEBUG:root:Line 0: [0.16601631 0.64263813 0.74796713]
DEBUG:root:Variance ratio: [0.99340644 0.00397251 0.00262106]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 1: [76.85028025 50.42512216 23.54193015]
DEBUG:root:Line 1: [0.68931954 0.58621198 0.42566899]
DEBUG:root:Variance ratio: [0.97687644 0.01949342 0.00363014]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 2: [77.45481562 54.52868753 28.92479379]
DEBUG:root:Line 2: [0.66699797 0.59568794 0.44751489]
DEBUG:root:Variance ratio: [0.96805593 0.02898377 0.0029603 ]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 3: [  6.12880491 116.82726776 130.2039006 ]
DEBUG:root:Line 3: [0.01353824 0.63296933 0.77405849]
DEBUG:root:Variance: 293.92301349025036
DEBUG:root:Variance ratio: 0.1007713768147954
DEBUG:root:Variance ratio: [0.96036936 0.03805517 0.00157547]
DEBUG:root:Iteration: 8
DEBUG:root:Centroid 0: [43.93810888 90.36332378 88.95759312]
DEBUG:root:Line 0: [0.1617019  0.64259732 0.74894671]
DEBUG:root:Variance ratio: [0.99318522 0.00417902 0.0

[0.91783349 1.15664898 0.58804845]
[152.51856344  30.81110892 225.72972475]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 0: [152.51856344  30.81110892 225.72972475]
DEBUG:root:Line 0: [0.91783349 1.15664898 0.58804845]
DEBUG:root:Variance ratio: [0.90038731 0.09816933 0.00144336]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 1: [66.73697764 46.99537128 23.82609688]
DEBUG:root:Line 1: [-0.11773016  0.60548462  0.787101  ]
DEBUG:root:Variance ratio: [9.33970128e-01 6.53052750e-02 7.24596654e-04]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 2: [48.55431641 92.3346004  84.72970596]
DEBUG:root:Line 2: [-0.61343957  0.37976688  0.69243701]
DEBUG:root:Variance: 484.56633720360793
DEBUG:root:Variance ratio: 0.16564256048749798


[0.46908234 0.08105    0.37478927]
[152.51856344  30.81110892 225.72972475]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 0: [152.51856344  30.81110892 225.72972475]
DEBUG:root:Line 0: [0.46908234 0.08105    0.37478927]
DEBUG:root:Variance ratio: [0.94466171 0.05420411 0.00113418]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 1: [62.0139481  49.53865566 28.84148962]
DEBUG:root:Line 1: [-0.19016568  0.58366393  0.78941335]
DEBUG:root:Variance ratio: [9.52344245e-01 4.70803920e-02 5.75362593e-04]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 2: [53.46982252 88.23626721 77.81161298]
DEBUG:root:Line 2: [-0.62082837  0.37550372  0.68816356]
DEBUG:root:Variance: 379.6802155449046
DEBUG:root:Variance ratio: 0.10299404448628807


[0.65240376 0.06671892 0.15380167]
[152.51856344  30.81110892 225.72972475]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 0: [152.51856344  30.81110892 225.72972475]
DEBUG:root:Line 0: [0.65240376 0.06671892 0.15380167]
DEBUG:root:Variance ratio: [9.62888373e-01 3.63397471e-02 7.71879841e-04]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 1: [57.53244244 55.35599882 37.45796076]
DEBUG:root:Line 1: [-0.2441566   0.57132907  0.78356279]
DEBUG:root:Variance ratio: [9.62508458e-01 3.69158475e-02 5.75694323e-04]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 2: [57.42565434 84.14412583 71.4351293 ]
DEBUG:root:Line 2: [-0.64835867  0.3534618   0.67431135]
DEBUG:root:Variance: 323.79225709140826
DEBUG:root:Variance ratio: 0.07460316870391731


[0.51176682 0.52082599 0.34203506]
[152.51856344  30.81110892 225.72972475]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 0: [152.51856344  30.81110892 225.72972475]
DEBUG:root:Line 0: [0.51176682 0.52082599 0.34203506]
DEBUG:root:Variance ratio: [9.67887768e-01 3.14357791e-02 6.76453163e-04]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 1: [54.71928623 59.33206689 43.20351281]
DEBUG:root:Line 1: [-0.26623242  0.56513686  0.78085891]
DEBUG:root:Variance ratio: [9.66697337e-01 3.27467474e-02 5.55915164e-04]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 2: [60.39169052 81.44040922 67.13197803]
DEBUG:root:Line 2: [-0.67013379  0.33488645  0.66239849]
DEBUG:root:Variance: 297.35424268780366
DEBUG:root:Variance ratio: 0.06541489490758734


[0.9909327  1.12936154 0.71384447]
[152.51856344  30.81110892 225.72972475]
Lose


DEBUG:root:Iteration: 11
DEBUG:root:Centroid 0: [152.51856344  30.81110892 225.72972475]
DEBUG:root:Line 0: [0.9909327  1.12936154 0.71384447]
DEBUG:root:Variance ratio: [9.69521781e-01 2.98306505e-02 6.47568993e-04]
DEBUG:root:Iteration: 11
DEBUG:root:Centroid 1: [53.39324787 61.1608328  45.91123435]
DEBUG:root:Line 1: [-0.27623015  0.5612415   0.78019541]
DEBUG:root:Variance ratio: [9.67128276e-01 3.23056731e-02 5.66050483e-04]
DEBUG:root:Iteration: 11
DEBUG:root:Centroid 2: [62.04455664 80.05946532 64.82295937]
DEBUG:root:Line 2: [-0.68226879  0.32508874  0.65484853]
DEBUG:root:Variance: 289.9268748897922
DEBUG:root:Variance ratio: 0.06334994305476656
DEBUG:root:Variance ratio: [8.98554649e-01 1.00812178e-01 6.33173714e-04]
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 0: [57.47781155 70.08349064 54.84007359]
DEBUG:root:Line 0: [-0.42510114  0.49474088  0.75797129]


[-0.23801412 -0.48222441  0.22936289]
[ 68.67568649  31.84176843 241.50739249]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 1: [ 68.67568649  31.84176843 241.50739249]
DEBUG:root:Line 1: [-0.23801412 -0.48222441  0.22936289]
DEBUG:root:Variance: 490.8346073011272
DEBUG:root:Variance ratio: 0.10144535133837462
DEBUG:root:Variance ratio: [9.04557111e-01 9.48213957e-02 6.21493153e-04]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [57.4039007  69.79943589 54.50443116]
DEBUG:root:Line 0: [-0.43734596  0.48901655  0.75471274]
DEBUG:root:Variance ratio: [0.90620488 0.07921038 0.01458474]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 1: [ 99.02702703 229.76576577 243.52252252]
DEBUG:root:Line 1: [-0.7138154  -0.57852681 -0.39468254]
DEBUG:root:Variance: 556.7632169726039
DEBUG:root:Variance ratio: 0.1892380102033599
DEBUG:root:Variance ratio: [8.96626997e-01 1.02705605e-01 6.67398394e-04]
DEBUG:root:Iteration: 3
DEBUG:root:Centroid 0: [58.37218383 67.8964368  51.83907595]
DEBUG:root:Line 0: [-0.46456003  0.47477431  0.74751142]
DEBUG:root:Variance ratio: [0.90062446 0.0944

DEBUG:root:Variance ratio: [0.91311528 0.08440448 0.00248024]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 0: [  8.98432514 115.34870962 127.73822986]
DEBUG:root:Line 0: [0.00806868 0.63300349 0.77410689]
DEBUG:root:Variance ratio: [0.9638867  0.0327775  0.00333579]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 1: [76.87976796 51.97314489 25.67395346]
DEBUG:root:Line 1: [0.67405662 0.59224004 0.44147414]
DEBUG:root:Variance: 193.77077480735875
DEBUG:root:Variance ratio: 0.12299801280318881
DEBUG:root:Variance ratio: [0.91311528 0.08440448 0.00248024]
DEBUG:root:Iteration: 8
DEBUG:root:Centroid 0: [  8.98432514 115.34870962 127.73822986]
DEBUG:root:Line 0: [0.00806868 0.63300349 0.77410689]
DEBUG:root:Variance ratio: [0.9638867  0.0327775  0.00333579]
DEBUG:root:Iteration: 8
DEBUG:root:Centroid 1: [76.87976796 51.97314489 25.67395346]
DEBUG:root:Line 1: [0.67405662 0.59224004 0.44147414]
DEBUG:root:Variance: 193.77077480735875
DEBUG:root:Variance ratio: 0.12299801280318881
DEBUG:root:Varia

[0.03000269 0.76320489 0.87597657]
[232.78300348 140.65252241 143.1159167 ]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 1: [232.78300348 140.65252241 143.1159167 ]
DEBUG:root:Line 1: [0.03000269 0.76320489 0.87597657]
DEBUG:root:Variance: 490.8346073011272
DEBUG:root:Variance ratio: 0.10144535133837462
DEBUG:root:Variance ratio: [9.03164690e-01 9.62058311e-02 6.29479256e-04]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [57.41722448 69.9063671  54.63779906]
DEBUG:root:Line 0: [-0.43337697  0.49082653  0.75582651]
DEBUG:root:Variance ratio: [0.83567417 0.13669193 0.0276339 ]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 1: [116.59375  242.90625  252.203125]
DEBUG:root:Line 1: [0.84483822 0.52108391 0.12132576]
DEBUG:root:Variance: 505.69555665021636
DEBUG:root:Variance ratio: 0.26116114193095996
DEBUG:root:Variance ratio: [9.04291172e-01 9.50859627e-02 6.22865588e-04]
DEBUG:root:Iteration: 3
DEBUG:root:Centroid 0: [57.52825304 69.40282691 53.96195407]
DEBUG:root:Line 0: [-0.44591923  0.48499405  0.75228772]
DEBUG:root:Variance ratio: [0.93976935 0.05589022 0.004

                red       green        blue
y_kmeans                                   
2          8.951081  115.406029  127.816934
3         76.867208   51.974364   25.681354
1


DEBUG:root:Iteration: 0
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 3
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 4
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 5
DEBUG:root:Centroid 0: [144.574517   157.85836

DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 5
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 6
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 8
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 9
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:

DEBUG:root:Line 3: [0.65206498 0.6988639  0.29393964]
DEBUG:root:Variance: 919.8471160367277
DEBUG:root:Variance ratio: 0.2133786868590121
DEBUG:root:Variance ratio: [0.92038428 0.06362044 0.01599528]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 0: [178.92375211 129.23282206 107.70520436]
DEBUG:root:Line 0: [0.53788267 0.59349639 0.59870215]
DEBUG:root:Variance ratio: [0.96097726 0.02979052 0.00923222]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 1: [169.43931921 169.06860021  71.31250434]
DEBUG:root:Line 1: [-0.64930252 -0.74798793 -0.13755105]
DEBUG:root:Variance ratio: [0.92314621 0.04647723 0.03037657]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 2: [130.58187885 162.77948537 100.78683265]
DEBUG:root:Line 2: [0.63256822 0.5939633  0.49705638]
DEBUG:root:Variance ratio: [0.98597601 0.00891975 0.00510424]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 3: [140.1311447  151.96103546  85.8038503 ]
DEBUG:root:Line 3: [-0.65396197 -0.69833595 -0.29096503]
DEBUG:root:Variance: 892.4737756706966


DEBUG:root:Iteration: 6
DEBUG:root:Centroid 0: [165.29701321 186.88965701  88.12458563]
DEBUG:root:Line 0: [-0.79914445 -0.59309115 -0.09803585]
DEBUG:root:Variance ratio: [0.93011721 0.04000956 0.02987323]
DEBUG:root:Iteration: 6
DEBUG:root:Centroid 1: [141.3826498  105.59145291  81.56732805]
DEBUG:root:Line 1: [0.73063389 0.47013774 0.49512082]
DEBUG:root:Variance ratio: [0.96741548 0.01896509 0.01361943]
DEBUG:root:Iteration: 6
DEBUG:root:Centroid 2: [128.6525878  148.66051391  95.39796649]
DEBUG:root:Line 2: [0.60877876 0.69162714 0.38863906]
DEBUG:root:Variance: 803.4159657068332
DEBUG:root:Variance ratio: 0.17786966209686902
DEBUG:root:Variance ratio: [0.92465246 0.06830577 0.00704177]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 0: [168.47128375 188.59704768  86.38318554]
DEBUG:root:Line 0: [-0.79152411 -0.59696735 -0.13084174]
DEBUG:root:Variance ratio: [0.93271441 0.04063857 0.02664702]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 1: [140.05701629 105.05854054  81.57411641]
DEBU

DEBUG:root:Centroid 0: [153.84777924 176.97477742  96.15232098]
DEBUG:root:Line 0: [-0.7416834  -0.64393891 -0.18774564]
DEBUG:root:Variance ratio: [0.94632266 0.03943716 0.01424018]
DEBUG:root:Iteration: 9
DEBUG:root:Centroid 1: [112.54622552  91.8335016   72.09441255]
DEBUG:root:Line 1: [0.73554218 0.49928154 0.45792538]
DEBUG:root:Variance: 774.4808137865718
DEBUG:root:Variance ratio: 0.16244747791077718
DEBUG:root:Variance ratio: [0.87245822 0.11423869 0.01330309]
DEBUG:root:Iteration: 10
DEBUG:root:Centroid 0: [157.58565574 181.34630411  97.84421177]
DEBUG:root:Line 0: [-0.77666288 -0.61106601 -0.15294802]
DEBUG:root:Variance ratio: [0.94355334 0.04038473 0.01606193]
DEBUG:root:Iteration: 10
DEBUG:root:Centroid 1: [106.36219689  88.87681991  69.91782044]
DEBUG:root:Line 1: [0.7465666  0.49507204 0.44445696]
DEBUG:root:Variance: 751.6207035292225
DEBUG:root:Variance ratio: 0.1839884375155953
DEBUG:root:Variance ratio: [0.87309208 0.11370342 0.01320449]
DEBUG:root:Iteration: 11
DEBU

[0.56308289 1.0131783  0.78248716]
[ 28.37858954 113.19870409 199.11058952]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 1: [ 28.37858954 113.19870409 199.11058952]
DEBUG:root:Line 1: [0.56308289 1.0131783  0.78248716]
DEBUG:root:Variance: 705.563029728174
DEBUG:root:Variance ratio: 0.11342469995092638
DEBUG:root:Variance ratio: [0.8865753  0.06635363 0.04707107]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Line 0: [0.66497777 0.69439574 0.27498932]


[0.68565551 1.05060571 0.36585159]
[ 28.37858954 113.19870409 199.11058952]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 1: [ 28.37858954 113.19870409 199.11058952]
DEBUG:root:Line 1: [0.68565551 1.05060571 0.36585159]
DEBUG:root:Variance: 705.563029728174
DEBUG:root:Variance ratio: 0.11342469995092638
DEBUG:root:Variance ratio: [0.88848773 0.06488392 0.04662835]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [144.42376564 157.72706224  90.5265421 ]
DEBUG:root:Line 0: [0.66564305 0.69594503 0.26940646]
DEBUG:root:Variance ratio: [0.70987424 0.18761823 0.10250753]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 1: [254.21698113 253.35849057 253.78301887]
DEBUG:root:Line 1: [-0.5811669  -0.59894579 -0.55091649]
DEBUG:root:Variance: 691.1618966415887
DEBUG:root:Variance ratio: 0.4016380302198764
DEBUG:root:Variance ratio: [0.89727629 0.06454255 0.03818116]
DEBUG:root:Iteration: 3
DEBUG:root:Centroid 0: [143.56764869 157.85744321  89.5846402 ]
DEBUG:root:Line 0: [-0.66385855 -0.70167654 -0.25873123]
DEBUG:root:Variance ratio: [0.93117518 0.0566508  0.01217402]
DEBUG:ro

DEBUG:root:Iteration: 7
DEBUG:root:Centroid 0: [144.78538178 171.46826673 105.93803277]
DEBUG:root:Line 0: [0.74099765 0.5410391  0.3977426 ]
DEBUG:root:Variance ratio: [0.94739434 0.03733397 0.0152717 ]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 1: [144.33127371 142.15865599  73.23133787]
DEBUG:root:Line 1: [0.6738374  0.71198791 0.19752562]
DEBUG:root:Variance: 761.406762754282
DEBUG:root:Variance ratio: 0.16010835767783133
DEBUG:root:Variance ratio: [0.89249545 0.05946306 0.04804149]
DEBUG:root:Iteration: 8
DEBUG:root:Centroid 0: [144.92556798 171.57483621 105.96824363]
DEBUG:root:Line 0: [0.74166347 0.54159048 0.39574618]
DEBUG:root:Variance ratio: [0.94739589 0.03741008 0.01519403]
DEBUG:root:Iteration: 8
DEBUG:root:Centroid 1: [144.16770134 141.96303132  73.11584172]
DEBUG:root:Line 1: [0.67409545 0.71189699 0.19697206]
DEBUG:root:Variance: 761.864009614018
DEBUG:root:Variance ratio: 0.16010866116253403
DEBUG:root:Variance ratio: [0.89252916 0.05949595 0.04797489]
DEBUG:root:Ite

                 red       green        blue
y_kmeans                                    
2         143.567649  157.857443   89.584640
3         192.936170  157.902826  146.758654
1


DEBUG:root:Iteration: 0
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 1
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 3
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 4
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 5
DEBUG:root:Centroid 0: [144.574517   157.85836

DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 5
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 6
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 8
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:root:Plane 0: [ 0.57572498 -0.71113387  0.4035212 ]
DEBUG:root:Variance: 292.80752858480975
DEBUG:root:Iteration: 9
DEBUG:root:Centroid 0: [144.574517   157.85836879  90.7507011 ]
DEBUG:

DEBUG:root:Line 3: [0.72587038 0.49453093 0.47807045]
DEBUG:root:Variance: 662.5527199991446
DEBUG:root:Variance ratio: 0.18534168188332328
DEBUG:root:Variance ratio: [0.93968163 0.05364309 0.00667528]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 0: [184.45992192 197.33555567  81.3085074 ]
DEBUG:root:Line 0: [-0.72291868 -0.62901168 -0.28588963]
DEBUG:root:Variance ratio: [0.93436716 0.0387696  0.02686324]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 1: [143.20983691 172.1819182  105.50820606]
DEBUG:root:Line 1: [0.73715015 0.59053357 0.32845053]
DEBUG:root:Variance ratio: [0.98322544 0.01195553 0.00481903]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 2: [93.26582653 76.66494693 61.59487461]
DEBUG:root:Line 2: [0.86556996 0.4017276  0.29900432]
DEBUG:root:Variance ratio: [0.96570805 0.0252487  0.00904326]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 3: [126.44354265 104.89292325  85.18033604]
DEBUG:root:Line 3: [0.67876795 0.5188282  0.51970316]
DEBUG:root:Variance: 722.9130586210165
DEBUG

DEBUG:root:Iteration: 6
DEBUG:root:Centroid 0: [137.48869619 167.02333024 103.82343052]
DEBUG:root:Line 0: [0.65533042 0.55808742 0.50899949]
DEBUG:root:Variance ratio: [0.96834938 0.02342428 0.00822634]
DEBUG:root:Iteration: 6
DEBUG:root:Centroid 1: [103.06699019  84.46415984  67.62747384]
DEBUG:root:Line 1: [0.80260312 0.45414572 0.38675561]
DEBUG:root:Variance ratio: [0.90286947 0.08757859 0.00955193]
DEBUG:root:Iteration: 6
DEBUG:root:Centroid 2: [185.04305315 199.82014244  90.07622822]
DEBUG:root:Line 2: [-0.7497608  -0.6212975  -0.22770192]
DEBUG:root:Variance: 682.215050273027
DEBUG:root:Variance ratio: 0.21679790148057926
DEBUG:root:Variance ratio: [0.92019764 0.04809916 0.0317032 ]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 0: [139.47441043 169.00211297 105.65786973]
DEBUG:root:Line 0: [0.69553151 0.56353367 0.44571933]
DEBUG:root:Variance ratio: [0.96812599 0.02379626 0.00807776]
DEBUG:root:Iteration: 7
DEBUG:root:Centroid 1: [102.9054153   84.30989506  67.49860347]
DEBUG:ro

DEBUG:root:Centroid 0: [155.4389794  180.74668439  96.49839758]
DEBUG:root:Line 0: [-0.80035127 -0.59896141 -0.02613577]
DEBUG:root:Variance ratio: [0.92840449 0.043553   0.02804251]
DEBUG:root:Iteration: 9
DEBUG:root:Centroid 1: [126.19414226 119.13617503  81.02681311]
DEBUG:root:Line 1: [0.65516035 0.63920394 0.40271979]
DEBUG:root:Variance: 905.1438164858001
DEBUG:root:Variance ratio: 0.16728787773794884
DEBUG:root:Variance ratio: [0.90321489 0.08575822 0.01102689]
DEBUG:root:Iteration: 10
DEBUG:root:Centroid 0: [155.5842792  180.83644191  96.55551465]
DEBUG:root:Line 0: [-0.79982051 -0.59948086 -0.03016375]
DEBUG:root:Variance ratio: [0.928403   0.04348299 0.02811402]
DEBUG:root:Iteration: 10
DEBUG:root:Centroid 1: [125.55410108 118.16155246  80.72233116]
DEBUG:root:Line 1: [0.65645588 0.63667298 0.40461487]
DEBUG:root:Variance: 906.2295928589
DEBUG:root:Variance ratio: 0.16838210941993176
DEBUG:root:Variance ratio: [0.90214748 0.08678616 0.01106636]
DEBUG:root:Iteration: 11
DEBUG:

DEBUG:root:Line 1: [-0.5391374  -0.8413776  -0.03761105]
DEBUG:root:Variance: 1009.8167076547767
DEBUG:root:Variance ratio: 0.18025838714720643
DEBUG:root:Variance ratio: [0.93192879 0.04293431 0.0251369 ]
DEBUG:root:Iteration: 4
DEBUG:root:Centroid 0: [130.9150707  151.88409619  91.00915268]
DEBUG:root:Line 0: [0.61877286 0.69230221 0.37126514]
DEBUG:root:Variance ratio: [0.89211223 0.08405291 0.02383486]
DEBUG:root:Iteration: 4
DEBUG:root:Centroid 1: [195.4351444  180.10343245  89.7883627 ]
DEBUG:root:Line 1: [-0.55456147 -0.82869803 -0.07563831]
DEBUG:root:Variance: 966.6014019605933
DEBUG:root:Variance ratio: 0.175958981186449
DEBUG:root:Variance ratio: [0.93644797 0.03886596 0.02468607]
DEBUG:root:Iteration: 5
DEBUG:root:Centroid 0: [129.66450877 151.4374925   91.52243068]
DEBUG:root:Line 0: [0.61769149 0.68784899 0.38120991]
DEBUG:root:Variance ratio: [0.89509789 0.08043916 0.02446294]
DEBUG:root:Iteration: 5
DEBUG:root:Centroid 1: [190.60746525 177.68209133  88.36807412]
DEBUG:r

[1.0046756  1.07334895 0.18413212]
[161.37191069   6.10987441 214.70163789]
Lose


DEBUG:root:Iteration: 1
DEBUG:root:Centroid 1: [161.37191069   6.10987441 214.70163789]
DEBUG:root:Line 1: [1.0046756  1.07334895 0.18413212]
DEBUG:root:Variance: 705.4749103540685
DEBUG:root:Variance ratio: 0.11341532485150722
DEBUG:root:Variance ratio: [0.88989142 0.06417396 0.04593462]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 0: [144.29138961 157.62999351  90.35146104]
DEBUG:root:Line 0: [0.66582032 0.69730502 0.2654223 ]
DEBUG:root:Variance ratio: [0.96246843 0.02544159 0.01208998]
DEBUG:root:Iteration: 2
DEBUG:root:Centroid 1: [253.30673317 245.56359102 244.07481297]
DEBUG:root:Line 1: [-0.12559921 -0.71118133 -0.69169788]
DEBUG:root:Variance: 697.4538865456094
DEBUG:root:Variance ratio: 0.14764015040486786
DEBUG:root:Variance ratio: [0.90595617 0.0638773  0.03016653]
DEBUG:root:Iteration: 3
DEBUG:root:Centroid 0: [142.41097245 157.95172497  89.37332647]
DEBUG:root:Line 0: [-0.65898869 -0.707317   -0.25580571]
DEBUG:root:Variance ratio: [0.93735529 0.04758258 0.01506213]
DEBUG:

                 red       green        blue
y_kmeans                                    
3         144.942362  173.183213  106.198803
4         103.262643   84.449783   68.054418
5         183.933292  196.282120   79.624970


In [29]:
i = [0, 0, 255, 255, 255]
row = [*i[0:2], 100, 100, 100]

In [30]:
row

[0, 0, 100, 100, 100]